# ArgoCD application manifest file - simple SHA-based tagging
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: easyshop
  namespace: argocd
  annotations:
    # Enable ArgoCD Image Updater for automatic deployments
    argocd-image-updater.argoproj.io/image-list: app=gibranf/easyshop
    
    # Use latest tag strategy instead of semver
    argocd-image-updater.argoproj.io/app.update-strategy: latest
    
    # Allow any tags (SHA tags don't follow semver pattern)
    argocd-image-updater.argoproj.io/app.allow-tags: regexp:^[a-f0-9]{7,40}$,latest
    
    # Write back to Git repository
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    
    # Simple commit message
    argocd-image-updater.argoproj.io/git-commit-message: "Update image tag to {{ .AppChanges }}"
    
    # Check for updates every 2 minutes
    argocd-image-updater.argoproj.io/update-frequency: 2m
    
    # Sync after CSI driver is installed
    argocd.argoproj.io/sync-wave: "2"

spec:
  project: easyshop-project  # Use custom project instead of default
  
  # Source repository configuration
  source:
    repoURL: https://github.com/iemafzalhassan/EasyShop-KIND.git
    targetRevision: tf-DevOps
    path: kubernetes
    
    # Use Kustomize for configuration management
    kustomize:
      images:
      - gibranf/easyshop:latest  # This will be updated by ArgoCD Image Updater
  
  # Destination cluster and namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: easyshop
  
  # Sync policy configuration
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
    
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  # Ignore differences for certain fields
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas  # Allow HPA to manage replicas
  
  - group: ""
    kind: Service
    jsonPointers:
    - /spec/loadBalancerIP
    - /status/loadBalancer/ingress
    
  # Application info
  info:
  - name: Description
    value: "EasyShop E-commerce Application with SHA-based tagging"
  - name: Tagging Strategy
    value: "Git SHA for unique identification"