#ArgoCD application manifest file: it automates and governs your app deployment and updates, ensuring your cluster state matches what’s in your repo
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: easyshop
  namespace: argocd
  annotations:
    # Enable ArgoCD Image Updater for automatic deployments
    argocd-image-updater.argoproj.io/image-list: app=gibranf/easyshop
    argocd-image-updater.argoproj.io/app.update-strategy: semver
    argocd-image-updater.argoproj.io/app.allow-tags: regexp:^v[0-9]+\.[0-9]+\.[0-9]+$
    #TODO: NEED TO WORK ON THE VERSIONING
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    # Sync after CSI driver is installed
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: easyshop-project  # Use custom project instead of default
  
  # Source repository configuration
  source:
    repoURL: https://github.com/iemafzalhassan/EasyShop-KIND.git
    targetRevision: tf-DevOps
    path: kubernetes
    
    # Use Kustomize for configuration management
    kustomize:
      images:
      - gibranf/easyshop:v1.0.0  # Semantic versioning - updated by ArgoCD Image Updater
  
  # Destination cluster and namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: easyshop
  
  # Sync policy configuration
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
    
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  # Ignore differences for certain fields
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas  # Allow HPA to manage replicas
  
  - group: ""
    kind: Service
    jsonPointers:
    - /spec/loadBalancerIP
    - /status/loadBalancer/ingress
    
  # Application info
  info:
  - name: Description
    value: "EasyShop E-commerce Application with Azure Key Vault integration"
  - name: Order
    value: "2"