apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: easyshop
  namespace: argocd
spec:
  description: EasyShop E-Commerce Application
  
  # Project sources
  sourceRepos:
  - https://github.com/iemafzalhassan/EasyShop-KIND
  
  # Destination clusters and namespaces
  destinations:
  - namespace: easyshop
    server: https://kubernetes.default.svc
  
  # Allowed resource kinds
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  
  # Namespace resource whitelist
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'