services:
  mongodb:
    image: mongo:latest
    container_name: easyshop-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - easyshop-network

  migration:
    build:
      context: .
      dockerfile: scripts/Dockerfile.migration
    container_name: easyshop-migration
    env_file:
      - .env.local
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - easyshop-network

  redis:
    image: redis:7.2-alpine
    container_name: easyshop-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - easyshop-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MONGODB_URI=mongodb://mongodb:27017/easyshop
        - REDIS_URI=redis://redis:6379
        - NEXTAUTH_URL=http://13.50.235.247
        - NEXT_PUBLIC_API_URL=http://13.50.235.247/api
        - NEXTAUTH_SECRET=HmaFjYZ2jbUK7Ef+wZrBiJei4ZNGBAJ5IdiOGAyQegw=
        - JWT_SECRET=e5e425764a34a2117ec2028bd53d6f1388e7b90aeae9fa7735f2469ea3a6cc8c
        - NODE_ENV=production
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/easyshop
      - REDIS_URI=redis://redis:6379
      - NEXTAUTH_URL=http://13.50.235.247
      - NEXT_PUBLIC_API_URL=http://13.50.235.247/api
      - NEXTAUTH_SECRET=HmaFjYZ2jbUK7Ef+wZrBiJei4ZNGBAJ5IdiOGAyQegw=
      - JWT_SECRET=e5e425764a34a2117ec2028bd53d6f1388e7b90aeae9fa7735f2469ea3a6cc8c
      - NODE_ENV=production
    env_file:
      - .env.local
    container_name: easyshop
    ports:
      - "3000:3000"
    # Remove the duplicate env_file declaration below
    depends_on:
      migration:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    networks:
      - easyshop-network
    restart: unless-stopped

networks:
  easyshop-network:
    name: easyshop-network

volumes:
  mongodb_data:
    name: mongodb_data
  redis_data:
    name: redis_data
