apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: easyshop
  namespace: argocd
  annotations:
    # Enable image updater for this app
    argocd-image-updater.argoproj.io/image-list: easyshop=easyshopacr.azurecr.io/easyshop:~1.0
    argocd-image-updater.argoproj.io/easyshop.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: https://github.com/iemafzalhassan/EasyShop-KIND
    targetRevision: main
    path: kubernetes  # Path to your Kubernetes manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: easyshop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true