kind: PersistentVolume
apiVersion: v1

metadata:
  name: mongodb-pv

spec:
  storageClassName: standard

  capacity:
    storage: 5Gi

  accessModes:
    - ReadWriteOnce

  hostPath:
    path: /data/mongodb
  persistentVolumeReclaimPolicy: Retain

  nodeAffinity:  # Add this section
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - easyshop-worker
