apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: easyshop
spec:
  storageClassName: ""  # <-- CRITICAL to match static PV
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

