
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: easyshop-keyvault-secrets
  namespace: easyshop
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    # Use the azurekeyvaultsecretsprovider identity - this is the one created for Key Vault access
    userAssignedIdentityClientID: "09c14e08-5697-42f4-8317-ab7e2522208a"
    keyvaultName: "easyshop-kv-09032127"  # Your actual Key Vault
    tenantId: "12751b8a-66a0-4d97-b3a1-76ff6a59ff4f"  # Your actual tenant
    objects: |
      array:
        - |
          objectName: es-mongodb-username
          objectType: secret
        - |
          objectName: es-mongodb-password
          objectType: secret
        - |
          objectName: es-mongodb-database
          objectType: secret
        - |
          objectName: es-mongodb-uri
          objectType: secret
        - |
          objectName: es-redis-password
          objectType: secret
        - |
          objectName: es-redis-uri
          objectType: secret
  secretObjects:
  - secretName: mongodb-keyvault-secret
    type: Opaque
    data:
    - objectName: es-mongodb-username
      key: username
    - objectName: es-mongodb-password
      key: password
    - objectName: es-mongodb-database
      key: database
    - objectName: es-mongodb-uri
      key: mongodb-uri
  - secretName: redis-keyvault-secret
    type: Opaque
    data:
    - objectName: es-redis-password
      key: password
    - objectName: es-redis-uri
      key: redis-uri
      