apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace for all resources
namespace: easyshop

# Start with essential resources only
resources:
- 01-namespace.yaml
- 04-configmap.yaml  
- 05-secrets.yaml
- 08a-blue-deployment.yml
- 08b-green-deployment.yaml
- 09-easyshop-service.yaml

# Use 'labels' instead of deprecated 'commonLabels'
labels:
- pairs:
    app.kubernetes.io/name: easyshop
    app.kubernetes.io/managed-by: kustomize
    environment: production

# Images to update
images:
- name: easyshop
  newTag: latest

# Simple replica overrides
replicas:
- name: easyshop-blue
  count: 2
- name: easyshop-green
  count: 2