apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace for all resources
namespace: easyshop

# Resources to deploy
resources:
- 00-priority-class.yaml
- 01-namespace.yaml
- 04-configmap.yaml
- 05-secrets.yaml
- 15-keyvault-secret-provider.yaml  # Azure Key Vault integration
- 06-mongodb-service.yaml
- 07-mongodb-statefulset.yaml  # Uses managed-csi (no need for 02-mongodb-pv.yaml)
- 08a-blue-deployment.yml      # ✅ BLUE deployment (initially active)
- 08b-green-deployment.yaml    # ✅ GREEN deployment (initially inactive)
- 09-easyshop-service.yaml     # Service that switches between blue/green
- 10-ingress.yaml              # Updated for AKS with buildandship.space domain
- 11-hpa.yaml
- 12-migration-job.yaml
- 13-redis-service.yaml
- 14-redis-deployment.yaml     # Updated with Key Vault secrets + authentication + ConfigMap
- cert-manager-issuer.yaml     # Let's Encrypt production issuer onlykustomize edit
- easyshop-certificate.yaml    # SSL certificates for buildandship.space

# Common labels applied to all resources - FIXED deprecated warning
labels:
- pairs:
    app.kubernetes.io/name: easyshop
    app.kubernetes.io/part-of: easyshop-platform
    app.kubernetes.io/managed-by: kustomize
    environment: production

# Common annotations
commonAnnotations:
  config.kubernetes.io/local-config: "true"

# Images to update (semantic versioning for better tracking)
images:
- name: easyshop
  newTag: latest

# Resource transformations
patches:
# Patch to use Azure storage class for MongoDB
- patch: |-
    - op: replace
      path: /spec/volumeClaimTemplates/0/spec/storageClassName
      value: managed-csi
  target:
    kind: StatefulSet
    name: mongodb

# Replica count overrides for production
replicas:
- name: easyshop-blue    # Blue deployment replicas
  count: 2
- name: easyshop-green   # Green deployment replicas  
  count: 2
- name: mongodb
  count: 1
- name: redis
  count: 1